name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  deployments: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  verify:
    runs-on: ubuntu-latest
    outputs:
      build_path: ${{ steps.check.outputs.build_path }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install Dependencies
        working-directory: rpg-game
        run: |
          npm install
          
      - name: Build Project
        working-directory: rpg-game
        run: |
          # Build the project - adjust this command based on your actual build script
          npm run build || npm run deploy
          
      - name: Debug directory structure
        run: |
          echo "Current directory structure:"
          find . -type f -name "index.html"
          
      - name: Locate index.html
        id: check
        shell: bash
        run: |
          # Check multiple possible locations
          possible_paths=(
            "rpg-game/deploy-ember/index.html"
            "rpg-game/deploy/index.html"
            "rpg-game/dist/index.html"
            "rpg-game/build/index.html"
            "rpg-game/public/index.html"
            "rpg-game/index.html"
          )
          
          for path in "${possible_paths[@]}"; do
            if [ -f "$path" ]; then
              echo "Found index.html at: $path"
              echo "build_path=$(dirname $path)" >> $GITHUB_OUTPUT
              exit 0
            fi
          done
          
          echo "::error::index.html not found in any expected location!"
          echo "Contents of rpg-game directory:"
          ls -R rpg-game/
          exit 1

  build:
    needs: verify
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
        
      - name: Prepare site root
        id: prepare
        run: |
          mkdir -p _site
          BUILD_PATH="${{ needs.verify.outputs.build_path }}"
          echo "Copying from $BUILD_PATH to _site"
          cp -rv "$BUILD_PATH"/* _site/
          
          echo "Contents of _site directory:"
          ls -la _site/
          
          if [ ! -f "_site/index.html" ]; then
            echo "::error::index.html not found in _site directory after copy"
            exit 1
          fi
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        timeout-minutes: 10
        
      - name: Verify deployment
        run: |
          if [ "${{ steps.deployment.outcome }}" != "success" ]; then
            echo "::error::Deployment failed!"
            exit 1
          fi 